#! /bin/sh

# Copyright (C) 2006 Nokia Corporation. 
# 
# Contact: Marius Vollmer <marius.vollmer@nokia.com>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation. 
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
 
# Real hackers don't read docs.
#
rm -rf /usr/share/doc/* /usr/share/man/* /usr/share/info/*
echo "Purged by docpurge" >/usr/share/doc/README
echo "Purged by docpurge" >/usr/share/man/README
echo "Purged by docpurge" >/usr/share/info/README
